include "application-local.conf"

app {
    env = ${?APP_ENV}
    env = "local" // Default to local
}

db {
    host = "localhost"
    host = ${?DB_HOST}
    port = 5432
    port = ${?DB_PORT}
    name = "quemfaz"
    name = ${?DB_NAME}
    user = "quemfaz"
    user = ${?DB_USER}
    pass = "quemfaz"
    pass = ${?DB_PASS}
}

sms {
    provider = "FAKE"
    provider = ${?SMS_PROVIDER}
}

otp {
    codeLength = 6
    expirationMinutes = 5
}

jwt {
    secret = "dev-secret-key-replace-in-production"
    issuer = "quemfaz"
    audience = "quemfaz-audience"
    expiresInMs = 3600000
}

admin {
    userIds = ["admin-1", "admin-2"]
    userIds = ${?ADMIN_USER_IDS}
}
